apiVersion: v1
kind: Service
metadata:
  labels:
    app: bedrock
    type: web
  name: bedrock
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: bedrock
    type: web

