apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: bedrock
    type: web
  name: bedrock-web
spec:
  maxReplicas: 7
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bedrock-web
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
