name: Release Charts

on:
  push:
    branches:
      - test
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # - name: Configure Git
      #   run: |
      #     git config user.name "mozmeao-helm"
      #     git config user.email "mozmeao-helm@users.noreply.github.com"

      - name: Build helm packages
        uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.CR_TOKEN }}
